#
# Makefile to add FIH driver for kernel driver build
obj-$(CONFIG_FIH_HWID) += fih_hwid.o
obj-$(CONFIG_FIH_INFO) += fih_info.o
obj-$(CONFIG_FIH_E2P) += fih_e2p.o
obj-$(CONFIG_FIH_CPU) += fih_cpu.o
obj-$(CONFIG_FIH_APR) += fih_apr.o
obj-y += fih_touch.o
obj-$(CONFIG_FIH_HALL_SENSOR) += hallsensor/
obj-y += fih_lcm.o
obj-$(CONFIG_FIH_DDRTEST) += fih_ddr_test.o
obj-y += fih_battery.o
obj-$(CONFIG_FIH_GPIO) += fih_gpio.o
