obj-$(CONFIG_AOD_FEATURE) += fih_msm_mdss_aod.o
obj-$(CONFIG_PANEL_POWER_CONTROL_FEATURE) += fih_msm_mdss_pwr.o
obj-$(CONFIG_FIH_PANEL_FEATURE) += fih_mdss_global.o
obj-$(CONFIG_PANEL_COLOR_MANAGERIAL) +=fih_mdss_color_managerial.o
clean:
	rm *.o
