dtb-$(CONFIG_ARCH_MSM8998) += \
  msm8998-mtp_A1N_EVB.dtb \
  msm8998-mtp_A1N_EVB_SS.dtb \
  msm8998-mtp_A1N_EVT.dtb \
  msm8998-mtp_A1N_EVT_SS.dtb \
  msm8998-mtp_A1N_EVT1_SS.dtb \
  msm8998-mtp_A1N_EVT1-1_SS.dtb \
  msm8998-mtp_A1N_EVT1-2_SS.dtb \
  msm8998-mtp_A1N_EVT1_5_SS.dtb \
  msm8998-mtp_A1N_DVT_SS.dtb \
  msm8998-mtp_A1N_DVT.dtb \
  msm8998-mtp_A1N_DVT_ROW.dtb \
  msm8998-mtp_A1N_DVT_CN.dtb \
  msm8998-mtp_A1N_DVT_US.dtb \
  msm8998-mtp_A1N_DVT_new_ROW.dtb \
  msm8998-mtp_A1N_DVT2_5_CN.dtb \
  msm8998-mtp_A1N_DVT3_new_ROW.dtb \
  msm8998-mtp_A1N_PVT_CN.dtb \
  msm8998-mtp_A1N_PVT_new_ROW.dtb \
  msm8998-mtp_A1N_MP_CN.dtb \
  msm8998-mtp_A1N_MP_new_ROW.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files := *.dtb
